"""
Django settings for ticket_booking project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
import os

# Ensure stdout/stderr use UTF-8 encoding on Windows consoles to avoid logging Unicode errorshhh
try:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Font paths - stored in assets/fonts directory
FONT_URL = [
    os.path.join(BASE_DIR, 'assets', 'fonts', 'Nunito-Bold.ttf'),
    os.path.join(BASE_DIR, 'assets', 'fonts', 'Nunito-Medium.ttf'),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Load .env in local development if present
if (Path(__file__).resolve().parent.parent / '.env').exists():
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-opx%#(^al3$yv0&^76_skx%e=9y4^b9xo^$w+*pkwn)42ks41+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

CORS_ALLOW_ALL_ORIGINS = True

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')

AUTH_USER_MODEL = 'accounts.EmployeeAccount'

# Redis config
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'vuquochoanganh2k3@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'tgai qoii itcl oroc')
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', 'abcdef');

# celery
from celery.schedules import crontab  # Thêm import ở đây

# Các cấu hình khác của Django và Celery
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL)
if CELERY_BROKER_URL and ('${REDIS_URL}' in CELERY_BROKER_URL or '$REDIS_URL' in CELERY_BROKER_URL):
    CELERY_BROKER_URL = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']  # Celery chấp nhận dữ liệu định dạng JSON
CELERY_TASK_SERIALIZER = 'json'  # Sử dụng JSON để serialize tasks

# Celery Beat schedule (công việc định kỳ)
CELERY_BEAT_SCHEDULE = {
    'update-section-prices-every-5-minutes': {
        'task': 'tickets.tasks.update_section_prices',  # Đảm bảo tên task chính xác
        'schedule': crontab(minute='*/1'),  # Cập nhật mỗi 5 phút
    },
}
FRONTEND_URL = 'http://localhost:5500'
# Google OAuth2
# Create an OAuth 2.0 Client ID in Google Cloud Console and set it here.
GOOGLE_CLIENT_ID = '798322275420-0rk6mm7g8nis62j2h4bjse6fbhtmk5pv.apps.googleusercontent.com'
# Facebook OAuth2 - set these in production/ENV
FACEBOOK_APP_ID = '4200485996929060'
FACEBOOK_APP_SECRET = '2311e7a08dfae3b341e097be27793be2'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'celery_tasks.log',  # Ghi log vào file celery_tasks.log
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps.tickets': {  # Logger cho app tickets
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Application definition
CORS_ALLOW_ALL_ORIGINS = True

INSTALLED_APPS = [
    'daphne',

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',
    'django_filters',
    'background_task',
    'celery',

    "apps.accounts",
    "apps.events",
    "apps.tickets",
    "apps.orders",
    "apps.promotions",
    "apps.returns",
    "apps.reports",
      "apps.chatbot"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ticket_booking.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ticket_booking.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE', 'ssss'),
        'USER': os.environ.get('MYSQL_USER', 'sasss'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', 'kcsss'),
        'HOST': os.environ.get('MYSQL_HOST', 'localhostsss'),
        'PORT': os.environ.get('MYSQL_PORT', '3306ss'),
    }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated', 
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 2000,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Ho_Chi_Minh"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ASGI_APPLICATION = 'ticket_booking.asgi.application'

SIMPLE_JWT = {
    'USER_ID_FIELD': 'username',  # Chỉ định rằng 'username' sẽ là trường duy nhất của người dùng
}

# settings.py
# AUTHENTICATION_BACKENDS = [
#     # 'apps.accounts.authentication_backend.CustomAuthenticationBackend',  # Đường dẫn tới backend tùy chỉnh
#     'django.contrib.auth.backends.ModelBackend',  # Backend mặc định của Django
# ]

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }


