app = "ticket-booking-be"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["heroku/python"]

[[services]]
  internal_port = 10000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true
