services:
  - type: web
    name: ticket-booking-backend-web
    runtime: python
    buildCommand: pip install -r ticket_booking/requirements.txt
    startCommand: bash entrypoint-web.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: "ticket_booking.settings"

  - type: worker
    name: ticket-booking-celery-worker
    runtime: python
    buildCommand: pip install -r ticket_booking/requirements.txt
    startCommand: bash entrypoint-worker.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: "ticket_booking.settings"

  - type: worker
    name: ticket-booking-celery-beat
    runtime: python
    buildCommand: pip install -r ticket_booking/requirements.txt
    startCommand: bash entrypoint-beat.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: "ticket_booking.settings"
