# Generated by Django 4.2.20 on 2025-11-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.stadium')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='SectionPrice',
            fields=[
                ('pricing_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.IntegerField()),
                ('is_closed', models.BooleanField(default=True)),
                ('sell_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.match')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.section')),
            ],
            options={
                'db_table': 'section_price',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_code', models.CharField(max_length=50, unique=True)),
                ('seat_number', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.section')),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('p_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateTimeField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.sectionprice')),
            ],
            options={
                'db_table': 'price_history',
            },
        ),
        migrations.AddConstraint(
            model_name='sectionprice',
            constraint=models.UniqueConstraint(fields=('match', 'section'), name='unique_match_section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('stadium', 'section_name'), name='unique_stadium_section_name'),
        ),
    ]
