# Generated by Django 4.2.20 on 2025-11-19 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.AutoField(primary_key=True, serialize=False)),
                ('league_name', models.CharField(max_length=255)),
                ('league_type', models.CharField(choices=[('round_robin', 'Đấu vòng tròn (V. League, Ngoại Hạng Anh)'), ('knockout', 'Đấu loại trực tiếp (Cúp Quốc gia)'), ('hybrid', 'Hỗn hợp (World Cup, C1, NBA Playoffs)'), ('friendly', 'Giao hữu'), ('other', 'Khác')], default='round_robin', max_length=20, verbose_name='Thể thức thi đấu')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('round', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.league')),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sport',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.AutoField(primary_key=True, serialize=False)),
                ('stadium_name', models.CharField(max_length=255, unique=True)),
                ('stadium_code', models.CharField(max_length=5, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('stadium_layouts', models.ImageField(blank=True, default='stadium_layouts/stadium-1.png', null=True, upload_to='stadium_layouts/')),
            ],
            options={
                'db_table': 'stadium',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, default='team_logos/default.webp', null=True, upload_to='team_logos/')),
                ('head_coach', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.sport')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('update', 'Cập nhật thông tin'), ('postpone', 'Hoãn'), ('cancel', 'Hủy'), ('reschedule', 'Dời lịch thi đấu')], max_length=50)),
                ('old_value', models.JSONField()),
                ('new_value', models.JSONField()),
                ('reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.match')),
            ],
            options={
                'db_table': 'match_history',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.stadium'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='events.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='events.team'),
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.sport'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('sport', 'team_name'), name='unique_team_name_per_sport'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('match_time', 'stadium'), name='unique_match_time_stadium'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('league', 'round', 'team_1', 'team_2'), name='unique_league_round_teams'),
        ),
    ]
