# Generated by Django 4.2.20 on 2025-12-04 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('tickets', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_code', models.CharField(max_length=100, unique=True)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm'), ('amount', 'Số tiền')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('usage_limit', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'db_table': 'promotion',
            },
        ),
        migrations.CreateModel(
            name='PromotionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.match')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotions.promotion')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.section')),
            ],
            options={
                'db_table': 'promotion_detail',
            },
        ),
        migrations.AddConstraint(
            model_name='promotiondetail',
            constraint=models.UniqueConstraint(fields=('promo', 'match', 'section'), name='unique_promo_match_section'),
        ),
    ]
