# Generated by Django 4.2.20 on 2025-12-04 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReturn',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_reason', models.TextField()),
                ('return_status', models.CharField(choices=[('pending', 'Đang chờ'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('completed', 'Hoàn tất')], max_length=50)),
                ('refund_method', models.CharField(choices=[('bank_card', 'Thẻ ngân hàng'), ('transfer', 'Chuyển khoản'), ('cash', 'Tiền mặt')], max_length=50)),
                ('return_time', models.DateTimeField(auto_now_add=True)),
                ('processed_time', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.orderdetail')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'db_table': 'ticket_return',
            },
        ),
    ]
